const PATH = {
  root: "/",
  admin: "/admin",
  signIn: "/dang-nhap",
  promotion: "/khuyen-mai",
  event: "/su-kien",
  profile: "/ho-so",
  chat: "/tin-nhan",
  notification: "/thong-bao",
  deposit_money: "/nap-tien",
  moderator: "/moderator",
  account_management: "/moderator/quan-ly-tai-khoan",
  user_debt: "/moderator/no-nguoi-dung",
  transaction_history_manager: "/moderator/lich-su-giao-dich",
  approval_topup_request: "/moderator/duyet-yeu-cau-nap-tien",
  send_notification: "/moderator/gui-thong-bao",
  view_feedback: "/moderator/xem-gop-y",
  played_time: "/moderator/thoi-gian-choi",
  account: "/account",
  account_info: "/account/thong-tin-tai-khoan",
  transaction_history: "/account/lich-su-giao-dich",
  debt_detail: "/account/chi-tiet-so-no",
  change_password: "/account/doi-mat-khau",
  feedback: "/account/gop-y",
};

export default PATH;
